# Generated by Django 3.2.6 on 2021-09-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='min_bid',
            new_name='current_price',
        ),
    ]
